llm_config:
  llm_base_url: https://api.siliconflow.cn/v1/
  llm_api_key: sk-rkaaajuldwebwppljkefybgzhtoslzjaukylvnivrzanbhjk
  models:
    base:
      model_name: Pro/deepseek-ai/DeepSeek-V3
      stream: False
      max_tokens: 8192
      temperature: 1.0
      top_p: 0.95
    reason:
      model_name: Pro/deepseek-ai/DeepSeek-R1
      stream: False
      max_tokens: 5120
      temperature: 1.0
      top_p: 0.95
    light:
      model_name: Qwen/QwQ-32B
      stream: False
      max_tokens: 1024
      temperature: 0.7
      top_p: 0.95
    vlm:
      model_name: Qwen/Qwen2.5-VL-32B-Instruct
      stream: False
      max_tokens: 1024
      temperature: 0.7
      top_p: 0.95

amap_config:
  amap_url: https://mcp.gaode.com/sse
  amap_api_key: 9844bb9e68e07657eb1222cf6e26f3ed

application_settings:
  log_level: INFO
  log_dir: ./output/logs
  results_dir: ./output/results
  default_language: en
  max_retries: 3
  default_currency: USD

db_config:
  docs_path: ./data/docs
  es_db_url: http://localhost:9200/
  es_db_usr: elastic
  es_db_pwd: 4AWa7iHgd/X:qdw&
  es_db_index: es_index
  es_db_local: data/esdata
  vector_db_path: ./data/vector_db
  embedding_model: intfloat/multilingual-e5-large-instruct
  embedding_type: "sentence_transformer"
  chunk_size: 1024
  chunk_overlap: 256
  search_type: similarity_score_threshold
  score_threshold: 0.855
  # lambda_mult: 0.25
  k: 5
  weights: [0.3, 0.7]
  
