api_keys:
  openai_api_key: your_openai_key_here
  google_api_key: your_google_key_here
  rapidapi_key: your_rapidapi_key_here
  instagram_username: your_instagram_username
  instagram_password: your_instagram_password

database_configuration:
  vector_db_path: ./data/vector_store

application_settings:
  log_level: INFO
  default_language: en
  max_retries: 3
  default_currency: USD